config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :products, only: [:index, :show, :create, :destroy] do
    resources :reviews, only: [:new, :create]
  end

  resource :account, only: [:show, :edit, :update]

  namespace :merchant do
    resources :products
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  validates :content, length: { minimum: 20 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/merchant/products_controller.rb
class Merchant::ProductsController < ApplicationController
  include DeviseCreateUsers::MerchantsHelper
  before_action :check_merchant, only:[ :new, :create, :edit, :update, :destroy ]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params.require(:product).permit(:name, :description, :price, :url))
    @product.save!
    redirect_to product_path(@product)
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(params.require(:product).permit(:name, :description, :price, :url))
    redirect_to product_path(@product)
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to merchant_products_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!

  def home
    @products = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only:[ :index, :show ]

  def index
    if params[:gender] == "0"
      @products = Product.where(gender: 0)
    elsif params[:gender] == "1"
      @products = Product.where(gender: 1)
    elsif params[:gender] == "2"
      @products = Product.where(gender: 2)
    else
      @products = Product.all
    end
  end

  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @review = Review.new(review_params)
    @review.product = @product
    if @review.save
      respond_to do |format|
        format.html { redirect_to product_path(@product) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'product/show' }
        format.js  # <-- idem
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_permitted_parameters

    protected

    # def after_sign_up_path_for(resource)
    #   edit_profile_path
    # end

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:merchant, :email, :password, :password_confirmation, :remember_me) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_create_users/merchants_helper.rb
module DeviseCreateUsers::MerchantsHelper
  def check_merchant
    if !current_user.merchant
      flash[:error] = "Don't be stupid haha"
      redirect_to root_path
    end
  end
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render "shared/footer" %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/merchant/products/edit.html.erb
<h1>Edit a product</h1>

<%= form_for [:merchant, @product] do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :price %>
<%= f.text_field :price %>
<%= f.label :description %>
<%= f.text_field :description %>
<%= f.label :URL %>
<%= f.text_field :url %>

<%= f.submit %>
<% end %>

app/views/merchant/products/index.html.erb
<h1>List of Products</h1>
<% @products.each do |product| %>
<h2><%= product.name %></h2>
<%= link_to "Delete this product", ([:merchant,product]), method: :delete %>
<% end %>


<% if current_user && current_user.merchant %>
<h3> Test </h3>
<% end %>

app/views/merchant/products/new.html.erb
<h1>Add new Product</h1>

<%= form_for [:merchant, @product] do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :price %>
<%= f.text_field :price %>
<%= f.label :description %>
<%= f.text_field :description %>
<%= f.label :URL %>
<%= f.text_field :url %>

<%= f.submit %>
<% end %>

app/views/merchant/products/show.html.erb
<h1> products detail</h1>

<h2><%= @product.name %></h2>
<p><%= @product.description %></p>
<p><%= @product.price %></p>
<p><%= @product.url %></p>

app/views/pages/home.html.erb
<div class=text-center>
  <div class="wrapper-home">
    <div class="logo-banner"> <%= image_tag "logo.png" %>
    </div>
  </div>
</div>
<br>
<div class="categories-home text-center">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4">
       <%= link_to products_path(gender: 0) do %>
       <div class="cat-card1">  <h1>men</h1> </div>
       <% end %>
     </div>

     <div class="col-xs-12 col-sm-4">
      <%= link_to products_path(gender: 1) do %>
      <div class="cat-card2">  <h1>woman</h1> </div>
      <% end %>
    </div>

    <div class="col-xs-12 col-sm-4">
      <%= link_to products_path(gender: 2) do %>
      <div class="cat-card3">  <h1>kids</h1> </div>
      <% end %>
    </div>
  </div>
</div>

<br>

<form action="" class="home-search text-center">
  <input type="text" class="home-search-input" placeholder="Search something">
  <button type="submit" class="home-search-btn">
    <i class="fa fa-search"></i>
  </button>
</form>
</div>
<br>

app/views/products/index.html.erb
<div class="text-center">
  <h1 >featured products</h1>
  <p>collection of nice products</p>
  </div>
<div class="products">
  <div class="featured-products">
    <div class="container">
      <div class="row">
        <% @products.each do |product| %>
        <ul class="product-card col-xs-12 col-sm-3 list-unstyled ">
          <h3> <%= product.name %> | <%= product.description %> </h3>
          <li>  <%= image_tag "http://unsplash.it/250/100" %></li>
          <li> € <%= product.price %></li>
          <li><a class="card-btn"><%= product.url %></a></li>
          <li> <%= link_to "show product", product_path(product) %></li>
        </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>


<% if current_user && current_user.merchant %>
<h3> Test </h3>
<% end %>

app/views/products/show.html.erb
<!--
<h1> products detail</h1>

<h2><%= @product.name %></h2>
<p><%= @product.description %></p>
<p><%= @product.price %></p>
<p><%= @product.url %></p>
 -->

<!-- app/views/restaurants/show.html.erb -->
<h1><%= @product.name %></h1>
<h2>
  <%= pluralize @product.reviews.size, "review" %>
</h2>

<div id="reviews">
  <% if @product.reviews.blank? %>
    Be the first to leave a review for <%= @product.name %>
  <% else %>
    <% @product.reviews.each do |review| %>
      <%= render 'reviews/show', review: review %>
    <% end %>
  <% end %>
</div>

<%= render 'reviews/form', product: @product, review: @review %>

app/views/reviews/_form.html.erb
<%= simple_form_for([ product, review ], remote: true) do |form| %>
  <%= form.input :content %>
  <%= form.button :submit %>
<% end %>

app/views/reviews/_show.html.erb
<p><%= review.content %></p>

app/views/reviews/create.js.erb
// app/views/reviews/create.js.erb
// Here you will write *javascript* that would be executed by the browser
<% if @review.errors.any? %>
  // Render new review form with errors
  $('#new_review').html("<%= j render 'reviews/form', product: @product, review: @review %>");
<% else %>
  // Create a paragraph for the new review. But hide it.
  var new_review = $("<%= j render 'reviews/show', review: @review %>").hide();
  // Add it to the DOM, at the end of the existing reviews. It's still hidden.
  $('#reviews').append(new_review);
  // Show the new review with an animation!
  new_review.slideDown();
  // Remove the text from the content textarea.
  $('#review_content').val('');
<% end %>

app/views/reviews/show.html.erb
<p><%= review.content %></p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div id="flash" class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div id="flash" class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer" id="footer">
  <ul class="list-inline">
    <li><a href=""><i class="fa fa-youtube"></i></a></li>
    <li><a href=""><i class="fa fa-instagram"></i></a></li>
    <li><a href=""><i class="fa fa-facebook"></i></a></li>
    <li><a href=""><i class="fa fa-twitter"></i></a></li>
  </ul>
  <div class="text-right">
    <p>Salespotr 2016 by Abdurrahman, Vallentino and Simone</p>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

    <!-- Notification -->
    <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
    <div class="badge-container">
      <i class="fa fa-envelope-o"></i>
      <div class="badge badge-blue">3</div>
    </div>
    <% end %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
            <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <% else %>

    <!-- Login text link -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>